### ISSUE TITLE
Dependencies

### ISSUE THREAD

**Issue by privefl** [nanxstats/stackgbm#1]
As catboost and lightgbm are not CRAN packages, you should probably move them to Suggests dependencies and add some `requireNamespace` (cf. http://r-pkgs.had.co.nz/description.html).

**Comment by nanxstats** [comment]
Interesting proposal. I think [by definition](https://cran.r-project.org/doc/manuals/r-release/R-exts.html#Package-Dependencies) they should be in `Imports` instead of `Suggests`:

> The ‘Suggests’ field... lists packages that are not necessarily needed. This includes packages used only in examples, tests or vignettes..., and packages loaded in the body of functions.

The only viable reason for moving them into `Suggests` would be for a CRAN submission - which I have no intentions to do (albeit the better exposure), because [compromises](https://stackoverflow.com/questions/42819420/r-package-dependencies-not-installed-from-additional-repositories-revisited) are required (removing namespace imports), plus it won't make the dependency installation any easier.

I will surely reconsider this if lightgbm and catboost made their way to CRAN one way.

**Comment by privefl** [comment]
Basically, `remotes::install_github("nanxstats/stackgbm")` won't work until I install the three packages.
But if I want to use only XGBoost, this would be much easier to install.

Anyway, your package.

**Comment by nanxstats** [comment]
That's a good point though - I updated the installation guide https://github.com/nanxstats/stackgbm/commit/dd0da95e452e74377c931067f3c1530bc05e9dc8 to make the order of things clearer. Thanks for the input!

**Comment by nanxstats** [comment]
**Update**: With the help of rlang, I was able to create some simple wrappers for calling the functions in these packages without making them hard dependencies. xgboost and lightgbm are moved to `Suggests` (don't have to but since they are both on CRAN), with catboost becoming a runtime dependency (not on CRAN as of now).
